import { createContext, useState, useEffect } from 'react';

export const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('language') || 'en';
    });

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    const translations = {
        en: {
            welcomeBack: 'Welcome Back,',
            fitnessOverview: 'Here is your daily fitness overview',
            dashboard: 'Dashboard',
            activities: 'Activities',
            nutrition: 'Nutrition',
            goals: 'Goals',
            sleep: 'Sleep',
            water: 'Water',
            achievements: 'Achievements',
            social: 'Social',
            logout: 'Logout',
            viewProfile: 'View Profile',

            totalActivities: 'Total Activities',
            caloriesBurned: 'Calories Burned',
            activeGoals: 'Active Goals',
            weeklyCalorieBurn: 'Weekly Calorie Burn',
            nutritionDistribution: 'Nutrition Distribution',
            recentActivities: 'Recent Activities',
            goalProgress: 'Goal Progress',
            dailyMotivation: 'Daily Motivation',
            motivationQuote: '"The only bad workout is the one that didn\'t happen!"',
            noRecentActivities: 'No recent activities found',
            startTracking: 'Start tracking your fitness journey today!',
            logActivity: 'Log Activity',
            viewAll: 'View All',
            manageGoals: 'Manage Goals',
            noActiveGoals: 'No active goals',
            setFirstGoal: 'Set your first goal to stay motivated!',
            createGoal: 'Create Goal',

            settings: 'Settings',
            accountInformation: 'Account Information',
            name: 'Name',
            email: 'Email',
            accountCreated: 'Account Created',
            appearance: 'Appearance',
            theme: 'Theme',
            chooseTheme: 'Choose your preferred theme',
            darkMode: 'Dark Mode',
            lightMode: 'Light Mode',
            language: 'Language',
            selectLanguage: 'Select Language',
            changePassword: 'Change Password',
            currentPassword: 'Current Password',
            newPassword: 'New Password',
            confirmNewPassword: 'Confirm New Password',
            saving: 'Saving...',
            notifications: 'Notifications',
            emailNotifications: 'Email Notifications',
            receiveEmailUpdates: 'Receive email updates about your activity',
            goalReminders: 'Goal Reminders',
            getRemindedGoals: 'Get reminded about your active goals',
            achievementAlerts: 'Achievement Alerts',
            celebrateAchievements: 'Celebrate when you unlock achievements',
            weeklyReports: 'Weekly Reports',
            receiveWeeklySummary: 'Receive a weekly summary of your progress',
            monthlyReports: 'Monthly Reports',
            getMonthlyAnalytics: 'Get detailed monthly analytics',
            soundEffects: 'Sound Effects',
            playSounds: 'Play sounds on interactions',
            privacyData: 'Privacy & Data',
            profileVisibility: 'Profile Visibility',
            makeProfileVisible: 'Make your profile visible to others',
            activitySharing: 'Activity Sharing',
            allowFriendsActivity: 'Allow friends to see your activities',
            autoSave: 'Auto-Save',
            autoSaveProgress: 'Automatically save your progress',
            unitsPreferences: 'Units & Preferences',
            measurementUnits: 'Measurement Units',
            chooseUnits: 'Choose metric or imperial units',
            timezone: 'Timezone',
            setTimezone: 'Set your local timezone',
            dataManagement: 'Data Management',
            exportData: 'Export Data',
            downloadData: 'Download a copy of your data',
            clearCache: 'Clear Cache',
            clearLocalCache: 'Clear local application cache',
            cacheCleared: 'Cache cleared successfully',
            dangerZone: 'Danger Zone',
            deleteAccount: 'Delete Account',
            deleteAccountWarning: 'Once you delete your account, there is no going back. Please be certain.',
            passwordsDoNotMatch: 'Passwords do not match',
            passwordTooShort: 'Password must be at least 6 characters',
            passwordChanged: 'Password changed successfully',
            passwordChangeFailed: 'Failed to change password',
            accountDeleted: 'Account deleted successfully',
            accountDeleteFailed: 'Failed to delete account',
            settingUpdated: 'Setting updated',
            dataExported: 'Data export started',

            myProfile: 'My Profile',
            editProfile: 'Edit Profile',
            emailCannotChange: 'Email address cannot be changed',
            age: 'Age',
            gender: 'Gender',
            male: 'Male',
            female: 'Female',
            other: 'Other',
            memberSince: 'Member Since',
            saveChanges: 'Save Changes',
            cancel: 'Cancel',
            fullName: 'Full Name',
            profileUpdated: 'Profile updated successfully',
            profileUpdateFailed: 'Failed to update profile',
            activitySummary: 'Activity Summary',

            activityLog: 'Activity Log',
            addActivity: 'Add New Activity',
            activityType: 'Activity Type',
            duration: 'Duration',
            durationPlaceholder: 'min',
            calories: 'Calories',
            caloriesPlaceholder: 'kcal',
            date: 'Date',
            notes: 'Notes',
            notesPlaceholder: 'How did it feel?',
            saveActivity: 'Save Activity',
            confirmDeleteActivity: 'Are you sure you want to delete this activity?',
            activityLogged: 'Activity logged successfully',
            activityLogFailed: 'Failed to log activity',
            activityDeleted: 'Activity deleted successfully',
            activityDeleteFailed: 'Failed to delete activity',
            reports: 'Reports',
            userManagement: 'User Management',
            adminDashboard: 'Admin Dashboard',
            systemOverview: 'System Overview',
        },
        rw: {
            welcomeBack: 'Murakaza neza,',
            fitnessOverview: 'Incamake yimyitozo yawe',
            dashboard: 'Incamake',
            activities: 'Ibikorwa',
            nutrition: 'Imirire',
            goals: 'Intego',
            sleep: 'Gusinzira',
            water: 'Amazi',
            achievements: 'Ibigwi',
            social: 'Imibanire',
            logout: 'Sohoka',
            viewProfile: 'Reba Porofayile',

            totalActivities: 'Ibikorwa Byose',
            caloriesBurned: 'Kalori Zatwitse',
            activeGoals: 'Intego Zihari',
            weeklyCalorieBurn: 'Kalori Zatwitse mu Cyumweru',
            nutritionDistribution: 'Imigabanyirize y\'Imirire',
            recentActivities: 'Ibikorwa bya Vuba',
            goalProgress: 'Aho Intego Zigeze',
            dailyMotivation: 'Imbaraga z\'Umunsi',
            motivationQuote: '"Nta myitozo mibi ibaho, uretse itakozwe!"',
            noRecentActivities: 'Nta bikorwa bya vuba byabonetse',
            startTracking: 'Tangira gukurikirana urugendo rwawe!',
            logActivity: 'Andika Igikorwa',
            viewAll: 'Reba Byose',
            manageGoals: 'Genzura Intego',
            noActiveGoals: 'Nta ntego zihari',
            setFirstGoal: 'Shiraho intego yawe ya mbere!',
            createGoal: 'Kora Intego',

            settings: 'Igenamiterere',
            accountInformation: 'Amakuru ya Konti',
            name: 'Izina',
            email: 'Imeli',
            accountCreated: 'Konti Yakozwe',
            appearance: 'Isura',
            theme: 'Insanganyamatsiko',
            chooseTheme: 'Hitamo insanganyamatsiko ukunda',
            darkMode: 'Umwijima',
            lightMode: 'Urumuri',
            language: 'Ururimi',
            selectLanguage: 'Hitamo Ururimi',
            changePassword: 'Hindura Ijambo ry\'Ibanga',
            currentPassword: 'Ijambo ry\'Ibanga rya None',
            newPassword: 'Ijambo ry\'Ibanga Rishya',
            confirmNewPassword: 'Emeza Ijambo ry\'Ibanga Rishya',
            saving: 'Birabikwa...',
            notifications: 'Amenyesha',
            emailNotifications: 'Amenyesha ya Imeli',
            receiveEmailUpdates: 'Akira amakuru agezweho kuri imeli',
            goalReminders: 'ibutsa Intego',
            getRemindedGoals: 'Ibuka intego zawe',
            achievementAlerts: 'Impuruza z\'Ibigwi',
            celebrateAchievements: 'Ishimire igihe ugeze ku bigwi',
            weeklyReports: 'Raporo za Buri Cyumweru',
            receiveWeeklySummary: 'Akira incamake ya buri cyumweru',
            monthlyReports: 'Raporo za Buri Kwezi',
            getMonthlyAnalytics: 'Bona isesengura rya buri kwezi',
            soundEffects: 'Amajwi',
            playSounds: 'Kina amajwi',
            privacyData: 'Amabanga & Amakuru',
            profileVisibility: 'Kugaragara kwa Porofayile',
            makeProfileVisible: 'Kora porofayile yawe igaragarire abandi',
            activitySharing: 'Gusangira Ibikorwa',
            allowFriendsActivity: 'Emerera inshuti kubona ibikorwa byawe',
            autoSave: 'Kubika Otomatike',
            autoSaveProgress: 'Bika iterambere ryawe byikora',
            unitsPreferences: 'Ibipimo & Ibyifuzo',
            measurementUnits: 'Ibipimo',
            chooseUnits: 'Hitamo metero cyangwa imperiyari',
            timezone: 'Isaha',
            setTimezone: 'Shiraho isaha yaho uherereye',
            dataManagement: 'Gucunga Amakuru',
            exportData: 'Kohereza Amakuru',
            downloadData: 'Kura kopi yamakuru yawe',
            clearCache: 'Siba Ububiko',
            clearLocalCache: 'Siba ububiko bwa porogaramu',
            cacheCleared: 'Ububiko bwasibwe neza',
            dangerZone: 'Ahatarwa',
            deleteAccount: 'Siba Konti',
            deleteAccountWarning: 'Numara gusiba konti yawe, nta kugaruka inyuma. Nyamuneka ubyemeze.',
            passwordsDoNotMatch: 'Amagambo yibanga ntahura',
            passwordTooShort: 'Ijambo ryibanga rigomba kugira inyuguti byibura 6',
            passwordChanged: 'Ijambo ryibanga ryahinduwe neza',
            passwordChangeFailed: 'Byananiranye guhindura ijambo ryibanga',
            accountDeleted: 'Konti yasibwe neza',
            accountDeleteFailed: 'Byananiranye gusiba konti',
            settingUpdated: 'Igenamiterere ryavuguruwe',
            dataExported: 'Kohereza amakuru byatangiye',

            myProfile: 'Porofayile Yanjye',
            editProfile: 'Hindura Porofayile',
            emailCannotChange: 'Imeli ntishobora guhinduka',
            age: 'Imyaka',
            gender: 'Igitsina',
            male: 'Gabo',
            female: 'Gore',
            other: 'Ibindi',
            memberSince: 'Umunyamuryango Kuva',
            saveChanges: 'Bika Impinduka',
            cancel: 'Kureka',
            fullName: 'Amazina Yose',
            profileUpdated: 'Porofayile yavuguruwe neza',
            profileUpdateFailed: 'Byananiranye kuvugurura porofayile',
            activitySummary: 'Incamake y\'Igikorwa',

            activityLog: 'Raporo y\'Igikorwa',
            addActivity: 'Ongeraho Igikorwa Gishya',
            activityType: 'Ubwoko bw\'Igikorwa',
            duration: 'Igihe',
            durationPlaceholder: 'min',
            calories: 'Kalori',
            caloriesPlaceholder: 'kcal',
            date: 'Itariki',
            notes: 'Inyandiko',
            notesPlaceholder: 'Wiyumvise ute?',
            saveActivity: 'Bika Igikorwa',
            confirmDeleteActivity: 'Uremeza ko ushaka gusiba iki gikorwa?',
            activityLogged: 'Igikorwa cyanditswe neza',
            activityLogFailed: 'Byananiranye kwandika igikorwa',
            activityDeleted: 'Igikorwa cyasibwe neza',
            activityDeleteFailed: 'Byananiranye gusiba igikorwa'
        },
        sw: {
            welcomeBack: 'Karibu Tena,',
            fitnessOverview: 'Hapa kuna muhtasari wako wa mazoezi',
            dashboard: 'Dashibodi',
            activities: 'Mazoezi',
            nutrition: 'Lishe',
            goals: 'Malengo',
            sleep: 'Usingizi',
            water: 'Maji',
            achievements: 'Mafanikio',
            social: 'Jamii',
            logout: 'Ondoka',
            viewProfile: 'Angalia Wasifu',

            totalActivities: 'Jumla ya Mazoezi',
            caloriesBurned: 'Kalori Zilizochomwa',
            activeGoals: 'Malengo Yaliyo Hai',
            weeklyCalorieBurn: 'Kalori za Wiki',
            nutritionDistribution: 'Mgawanyo wa Lishe',
            recentActivities: 'Mazoezi ya Hivi Karibuni',
            goalProgress: 'Maendeleo ya Malengo',
            dailyMotivation: 'Hamasa ya Siku',
            motivationQuote: '"Zoezi baya pekee ni lile ambalo halikufanyika!"',
            noRecentActivities: 'Hakuna mazoezi ya hivi karibuni',
            startTracking: 'Anza kufuatilia safari yako ya mazoezi leo!',
            logActivity: 'Rekodi Zoezi',
            viewAll: 'Angalia Yote',
            manageGoals: 'Simamia Malengo',
            noActiveGoals: 'Hakuna malengo yaliyo hai',
            setFirstGoal: 'Weka lengo lako la kwanza!',
            createGoal: 'Unda Lengo',

            settings: 'Mipangilio',
            accountInformation: 'Taarifa za Akaunti',
            name: 'Jina',
            email: 'Baruapepe',
            accountCreated: 'Akaunti Iliundwa',
            appearance: 'Muonekano',
            theme: 'Mandhari',
            chooseTheme: 'Chagua mandhari unayopenda',
            darkMode: 'Hali ya Giza',
            lightMode: 'Hali ya Mwanga',
            language: 'Lugha',
            selectLanguage: 'Chagua Lugha',
            changePassword: 'Badilisha Nenosiri',
            currentPassword: 'Nenosiri la Sasa',
            newPassword: 'Nenosiri Jipya',
            confirmNewPassword: 'Thibitisha Nenosiri Jipya',
            saving: 'Inahifadhi...',
            notifications: 'Arifa',
            emailNotifications: 'Arifa za Baruapepe',
            receiveEmailUpdates: 'Pokea taarifa kupitia baruapepe',
            goalReminders: 'Vikumbusho vya Malengo',
            getRemindedGoals: 'Kumbushwa kuhusu malengo yako',
            achievementAlerts: 'Arifa za Mafanikio',
            celebrateAchievements: 'Sherehekea unapofikia mafanikio',
            weeklyReports: 'Ripoti za Wiki',
            receiveWeeklySummary: 'Pokea muhtasari wa wiki',
            monthlyReports: 'Ripoti za Mwezi',
            getMonthlyAnalytics: 'Pata uchambuzi wa mwezi',
            soundEffects: 'Sauti',
            playSounds: 'Cheza sauti wakati wa matumizi',
            privacyData: 'Faragha na Data',
            profileVisibility: 'Kuonekana kwa Wasifu',
            makeProfileVisible: 'Fanya wasifu wako uonekane kwa wengine',
            activitySharing: 'Kushiriki Mazoezi',
            allowFriendsActivity: 'Ruhusu marafiki kuona mazoezi yako',
            autoSave: 'Kuhifadhi Kiotomatiki',
            autoSaveProgress: 'Hifadhi maendeleo yako kiotomatiki',
            unitsPreferences: 'Vipimo na Mapendeleo',
            measurementUnits: 'Vipimo',
            chooseUnits: 'Chagua vipimo vya mita au kifalme',
            timezone: 'Saa za Eneo',
            setTimezone: 'Weka saa za eneo lako',
            dataManagement: 'Usimamizi wa Data',
            exportData: 'Hamisha Data',
            downloadData: 'Pakua nakala ya data yako',
            clearCache: 'Futa Akiba',
            clearLocalCache: 'Futa akiba ya programu',
            cacheCleared: 'Akiba imefutwa',
            dangerZone: 'Eneo la Hatari',
            deleteAccount: 'Futa Akaunti',
            deleteAccountWarning: 'Ukifuta akaunti yako, huwezi kurudi nyuma. Tafadhali thibitisha.',
            passwordsDoNotMatch: 'Nywila hazilingani',
            passwordTooShort: 'Nenosiri lazima liwe na angalau herufi 6',
            passwordChanged: 'Nenosiri limebadilishwa',
            passwordChangeFailed: 'Imeshindwa kubadilisha nenosiri',
            accountDeleted: 'Akaunti imefutwa',
            accountDeleteFailed: 'Imeshindwa kufuta akaunti',
            settingUpdated: 'Mipangilio imesasishwa',
            dataExported: 'Uhamishaji wa data umeanza',

            myProfile: 'Wasifu Wangu',
            editProfile: 'Hariri Wasifu',
            emailCannotChange: 'Baruapepe haiwezi kubadilishwa',
            age: 'Umri',
            gender: 'Jinsia',
            male: 'Mwanaume',
            female: 'Mwanamke',
            other: 'Nyingine',
            memberSince: 'Mwanachama Tangu',
            saveChanges: 'Hifadhi Mabadiliko',
            cancel: 'Ghairi',
            fullName: 'Jina Kamili',
            profileUpdated: 'Wasifu umesasishwa',
            profileUpdateFailed: 'Imeshindwa kusasisha wasifu',
            activitySummary: 'Muhtasari wa Mazoezi',

            activityLog: 'Kumbukumbu ya Mazoezi',
            addActivity: 'Ongeza Zoezi Jipya',
            activityType: 'Aina ya Zoezi',
            duration: 'Muda',
            durationPlaceholder: 'dak',
            calories: 'Kalori',
            caloriesPlaceholder: 'kcal',
            date: 'Tarehe',
            notes: 'Vidokezo',
            notesPlaceholder: 'Ulijisikiaje?',
            saveActivity: 'Hifadhi Zoezi',
            confirmDeleteActivity: 'Una uhakika unataka kufuta zoezi hili?',
            activityLogged: 'Zoezi limerekodiwa',
            activityLogFailed: 'Imeshindwa kurekodi zoezi',
            activityDeleted: 'Zoezi limefutwa',
            activityDeleteFailed: 'Imeshindwa kufuta zoezi'
        },
        fr: {
            welcomeBack: 'Bon retour,',
            fitnessOverview: 'Voici votre aperçu quotidien de la forme physique',
            dashboard: 'Tableau de bord',
            activities: 'Activités',
            nutrition: 'Nutrition',
            goals: 'Objectifs',
            sleep: 'Sommeil',
            water: 'Eau',
            achievements: 'Succès',
            social: 'Social',
            logout: 'Déconnexion',
            viewProfile: 'Voir le profil',

            totalActivities: 'Total des activités',
            caloriesBurned: 'Calories brûlées',
            activeGoals: 'Objectifs actifs',
            weeklyCalorieBurn: 'Brûlure calorique hebdomadaire',
            nutritionDistribution: 'Répartition nutritionnelle',
            recentActivities: 'Activités récentes',
            goalProgress: 'Progrès des objectifs',
            dailyMotivation: 'Motivation quotidienne',
            motivationQuote: '"Le seul mauvais entraînement est celui qui n\'a pas eu lieu !"',
            noRecentActivities: 'Aucune activité récente trouvée',
            startTracking: 'Commencez à suivre votre parcours de fitness dès aujourd\'hui !',
            logActivity: 'Enregistrer l\'activité',
            viewAll: 'Voir tout',
            manageGoals: 'Gérer les objectifs',
            noActiveGoals: 'Aucun objectif actif',
            setFirstGoal: 'Fixez votre premier objectif pour rester motivé !',
            createGoal: 'Créer un objectif',
            reports: 'Rapports',
            userManagement: 'Gestion des Utilisateurs',
            adminDashboard: 'Tableau de bord Admin',
            systemOverview: 'Aperçu du Système',

            settings: 'Paramètres',
            accountInformation: 'Informations sur le compte',
            name: 'Nom',
            email: 'Email',
            accountCreated: 'Compte créé',
            appearance: 'Apparence',
            theme: 'Thème',
            chooseTheme: 'Choisissez votre thème préféré',
            darkMode: 'Mode Sombre',
            lightMode: 'Mode Clair',
            language: 'Langue',
            selectLanguage: 'Choisir la langue',
            changePassword: 'Changer le mot de passe',
            currentPassword: 'Mot de passe actuel',
            newPassword: 'Nouveau mot de passe',
            confirmNewPassword: 'Confirmer le nouveau mot de passe',
            saving: 'Enregistrement...',
            notifications: 'Notifications',
            emailNotifications: 'Notifications par email',
            receiveEmailUpdates: 'Recevoir des mises à jour par email sur votre activité',
            goalReminders: 'Rappels d\'objectifs',
            getRemindedGoals: 'Soyez rappelé de vos objectifs actifs',
            achievementAlerts: 'Alertes de succès',
            celebrateAchievements: 'Célébrez lorsque vous débloquez des succès',
            weeklyReports: 'Rapports hebdomadaires',
            receiveWeeklySummary: 'Recevez un résumé hebdomadaire de vos progrès',
            monthlyReports: 'Rapports mensuels',
            getMonthlyAnalytics: 'Obtenez des analyses mensuelles détaillées',
            soundEffects: 'Effets sonores',
            playSounds: 'Jouer des sons lors des interactions',
            privacyData: 'Confidentialité et données',
            profileVisibility: 'Visibilité du profil',
            makeProfileVisible: 'Rendre votre profil visible aux autres',
            activitySharing: 'Partage d\'activité',
            allowFriendsActivity: 'Permettre aux amis de voir vos activités',
            autoSave: 'Sauvegarde automatique',
            autoSaveProgress: 'Sauvegarder automatiquement vos progrès',
            unitsPreferences: 'Unités et préférences',
            measurementUnits: 'Unités de mesure',
            chooseUnits: 'Choisissez les unités métriques ou impériales',
            timezone: 'Fuseau horaire',
            setTimezone: 'Définir votre fuseau horaire local',
            dataManagement: 'Gestion des données',
            exportData: 'Exporter les données',
            downloadData: 'Télécharger une copie de vos données',
            clearCache: 'Vider le cache',
            clearLocalCache: 'Vider le cache local de l\'application',
            cacheCleared: 'Cache vidé avec succès',
            dangerZone: 'Zone de danger',
            deleteAccount: 'Supprimer le compte',
            deleteAccountWarning: 'Une fois que vous supprimez votre compte, il n\'y a pas de retour en arrière. Veuillez être certain.',
            passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
            passwordTooShort: 'Le mot de passe doit contenir au moins 6 caractères',
            passwordChanged: 'Mot de passe changé avec succès',
            passwordChangeFailed: 'Échec du changement de mot de passe',
            accountDeleted: 'Compte supprimé avec succès',
            accountDeleteFailed: 'Échec de la suppression du compte',
            settingUpdated: 'Paramètre mis à jour',
            dataExported: 'L\'exportation des données a commencé',

            myProfile: 'Mon profil',
            editProfile: 'Modifier le profil',
            emailCannotChange: 'L\'adresse email ne peut pas être modifiée',
            age: 'Âge',
            gender: 'Genre',
            male: 'Homme',
            female: 'Femme',
            other: 'Autre',
            memberSince: 'Membre depuis',
            saveChanges: 'Enregistrer les modifications',
            cancel: 'Annuler',
            fullName: 'Nom complet',
            profileUpdated: 'Profil mis à jour avec succès',
            profileUpdateFailed: 'Échec de la mise à jour du profil',
            activitySummary: 'Résumé de l\'activité',

            activityLog: 'Journal d\'activité',
            addActivity: 'Ajouter une nouvelle activité',
            activityType: 'Type d\'activité',
            duration: 'Durée',
            durationPlaceholder: 'min',
            calories: 'Calories',
            caloriesPlaceholder: 'kcal',
            date: 'Date',
            notes: 'Notes',
            notesPlaceholder: 'Comment vous sentiez-vous ?',
            saveActivity: 'Enregistrer l\'activité',
            confirmDeleteActivity: 'Êtes-vous sûr de vouloir supprimer cette activité ?',
            activityLogged: 'Activité enregistrée avec succès',
            activityLogFailed: 'Échec de l\'enregistrement de l\'activité',
            activityDeleted: 'Activité supprimée avec succès',
            activityDeleteFailed: 'Échec de la suppression de l\'activité'
        }
    };

    const t = (key) => {
        return translations[language]?.[key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}
